---
driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/build']

provisioner:
  name: chef_zero
  require_chef_omnibus: true

attribute_defaults: &attribute_defaults
  build_user:          vagrant
  build_user_group:    vagrant
  build_user_password: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
suites:
- name: default
  data_bags_path: <%= "#{ENV['CHEF_REPO']}/data_bags" %>
  run_list:
    - recipe[build::default]
  attributes:
    build:
      <<: *attribute_defaults
      dist: 'precise'
- name: backport
  data_bags_path: <%= "#{ENV['CHEF_REPO']}/data_bags" %>
  run_list:
    - recipe[build::backport]
  attributes:
    build:
      <<: *attribute_defaults
      dist: 'precise'
- name: omnibus
  data_bags_path: <%= "#{ENV['CHEF_REPO']}/data_bags" %>
  run_list:
    - recipe[build::omnibus]
  attributes:
    build:
      <<: *attribute_defaults
      dist: 'precise'
